language: perl
perl:
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'

matrix:
   fast_finish: true
   include:
     - perl: '5.20'
       env: COVERAGE=1

sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls #Make sure to shoot it over to coveralls
  - cpanm --quiet --notest Test::Spelling Test::NoTabs Test::EOL #Looks like they were missed by haarg's stuff

branches:
   only:
      - /^build/

before_script:
  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
after_success:
  - coverage-report
